### ISSUE TITLE
moving to apps/v1 from extensions/v1beta1

### ISSUE THREAD

**Issue by unireverbcity** [bhavaniravi/airflow-kube-setup#1]
hI! is there any new version of config files with updated apiVersion definitions and selector definitions for new versions of Kubernetes?
thank you

**Comment by bhavaniravi** [comment]
Please feel free to update it and raise a PR

**Comment by kaushikarvind** [comment]
I'v updated the config files to new apiVersion & the deploy.sh executes successfully to create all pods. The LodeBalancer service exposes a port too, but i'm not able to see the airflow webserver application on the browser.
I'm running this setup on a local k8s setup on my laptop (with 1 master & 1 node running on Oracle VM Virtualbox VMs).

Is there any specific way to access the application? Am I missing something?
