### ISSUE TITLE
Trouble getting kubernetsPodOperator in Dag running

### ISSUE THREAD

**Issue by jgn1982** [bhavaniravi/airflow-kube-setup#11]
This repo and the blog post are really good but I'm having difficulty using the KubernetsPodOperator. When I use it I get a /root/.kube/config not found in the log on Airflow. I'm running the example_kubernetes_operator DAG. Any suggestions?

**Comment by bhavaniravi** [comment]
The `example_kubernetes_operator` for airflow 1.10 comes with `in-cluster=False` and `namespace=default`.  Chaning those two should fix it.

```
k = KubernetesPodOperator(
    namespace='airflow-example',
    in_cluster=True,
   ...
)
```

### More info

`/root/.kube/config` is looked up when airflow is running on a non-kubernetes env(say a VM). please not that the repo doesn't support the case where airflow runs outside of kuberenetes.

**Comment by jgn1982** [comment]
Thank you. This pointed me in the right direction. I have another question but will pose in another issue thread.
