### ISSUE TITLE
out of the box issues with namespace airflow-example

### ISSUE THREAD

**Issue by jgn1982** [bhavaniravi/airflow-kube-setup#12]
I cloned the git and made the specific changes according to the readme/blog post. When the airflow.yaml is created and launched I get an error that it cannot find airflow-configmaps. 

MountVolume.SetUp failed for volume "airflow-configmap" : configmap "airflow-configmap" not found.

If I change all the namespace values to default in airflow.yaml this works well enough but that doesn't seem to be the intended design of this repo. The webserver/scheduler seems to be designed to work within their own namespace and communicate back to the default namespace for the DB backend/configmaps.

Am I missing a setup step?

**Comment by bhavaniravi** [comment]
Hey @lfreina Good catch, I went back and forth on the namespace script and looks like I missed a command in `deploy.sh` causing the trouble. While I update the code please use the following command to switch to airflow namespace and followed by creating other resources

```
kubectl config set-context --current --namespace=airflow-example  
```

**Comment by jgn1982** [comment]
Great. This worked well. Adding this to the deploy.sh script binds all the resources under one namespace so they can communicate. 

Closing.
