### ISSUE TITLE
issue with rbac permission resource

### ISSUE THREAD

**Issue by jgn1982** [bhavaniravi/airflow-kube-setup#13]
When launching a custom DAG using kubernetesPodOperator airflow correctly launched the pod but returned a failed status on the job. The log produced this error:

"status":"Failure","message":"pods \\"airflow-dag-c4eaf498\\" is forbidden: User \\"system:serviceaccount:airflow-example:airflow\\" cannot get resource \\"pods/log\\" 

This was caused by the rbac group not having correct permissions in the resources. It should include "pods/log" to allow the airflow user to read the pod logs. 

Once this edit was made the logs were accessed and airflow showed success.

https://kubernetes.io/docs/reference/access-authn-authz/rbac/ REF: Referring to resources.

**Comment by bhavaniravi** [comment]
Great that you are using the repo and finding these issues. Can you raise a PR with the respective change?

**Comment by jgn1982** [comment]
PR created. closing.
