### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by Lakshmi-Chaitra** [bhavaniravi/airflow-kube-setup#17]
The repo overall is very helpful but When I try to deploy the code. the airflow pod is failing at init. with init:error
Following is the error I see:
![image](https://user-images.githubusercontent.com/63247826/111336759-83f90d00-8643-11eb-9c4f-199a8739a474.png)

I think sqlalchemy modules are installed with the airflow image. I tried to install sql-alchemy packages separately and still see the same issue. 
Can you please guide me through this.

**Comment by bhavaniravi** [comment]
Which version of sqlalchemy are you installing?

**Comment by Lakshmi-Chaitra** [comment]
> Which version of sqlalchemy are you installing?
I'm using the default version which ever comes with airflow 1.10.10. What version of sqlalchemy should this airflow version support? I also tried 1.3.19 I still see error.

**Comment by bhavaniravi** [comment]
There is some issue with your DB, clear out airflow DB and try again. This issue is not specific to the script

**Comment by sergioromerocarrizosa** [comment]
Installing "RUN pip install SQLAlchemy==1.3.23" in Dockerfile works for me
