### ISSUE TITLE
error while running airflow yaml 

### ISSUE THREAD

**Issue by rajendraprasad9** [bhavaniravi/airflow-kube-setup#8]
error: error validating "airflow.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

error while running airflow yaml

**Comment by rajendraprasad9** [comment]
any update on my issue

**Comment by bhavaniravi** [comment]
Which version of Kubernetes are you using?

**Comment by rajendraprasad9** [comment]
Kubernetes 1.19

**Comment by rajendraprasad9** [comment]
i am not able to change spec in Kubernetes 1.19

**Comment by lfreina** [comment]
Actually the pull-request I am having here https://github.com/bhavaniravi/airflow-kube-setup/pull/6/files uses the selector you are missing @rajendraprasad9. Maybe if it is not approved yet it can still be useful for you to move forward :wink:

**Comment by bhavaniravi** [comment]
#6 Has a lot more changes than the selector fix, that's why I am wary of merging it before testing. Will create another PR for the selector test it and merge it today
